# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      args: ["--profile", "black", "--filter-files"]
      hooks:
          - id: isort
    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
          - id: black

    - repo: local
      hooks:
        - id: check-readme-index
          name: check-readme-index
          entry: bash -c 'diff <(head -n 1 README.md) <(head -n 1 docs/API/index.md) || { echo "README.md and docs/API/index.md differ"; sed -i "1s/.*/# sklearo/" README.md; sed -i "1s/.*/# Homepage/" docs/API/index.md; }'
          language: system
          types: [python]
          pass_filenames: false
