name: Tests
on: [push]
jobs:
  pre-commit:
    name: Run pre-commit on all files
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up uv with Python 3.11
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.11"

      - name: Sync dev dependencies with uv
        run: uv sync --dev

      - name: Run pre-commit on all files
        run: uv run pre-commit run --all-files

  pytest:
    name: Run unit-tests using pytest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up uv with Python 3.11
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.11"

      - name: Sync dev dependencies with uv
        run: uv sync --dev

      - name: Run pytest tests
        run: uv run pytest -q
